services:
  php:
    build: .
    restart: always 
    ports: 
      - "8080:443" # accès web http://localhost:8080
    volumes: 
      - ./public:/app/public
      - ./src:/app/src
    depends_on:
      - dbTaskManager

  dbTaskManager:
    container_name: TaskManager
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - TaskManager:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  TaskManager:

