services:
  dbPomotask:
    container_name: TaskManager
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - TaskManager:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: Adminer
    image: adminer
    restart: always
    ports: 
      - "8085:8080"

volumes:
  TaskManager: